### ISSUE TITLE
[Bug Report]cannot up all

### ISSUE THREAD

**Issue by stydxm** [BaiMeow/wg-quick-op#3]
`wg-quick-op * up` is descrbed in readme but prints(`xxx` is a file name in current directory):
```
Error: unknown command "xxx" for "wg-quick-op"
Run 'wg-quick-op --help' for usage.
```
And if you use this command in an empty dir, it prints:
```
Error: unknown command "*" for "wg-quick-op"

Did you mean this?
        up

Run 'wg-quick-op --help' for usage.
```
Also, `wg-quick` originally, it's a typo I think.

**Comment by BaiMeow** [comment]
up *

**Comment by stydxm** [comment]
> up *

![](https://github.com/BaiMeow/wg-quick-op/assets/62790279/4784308b-8a42-403a-9b2d-0d4271b58211)

**Comment by ljcbaby** [comment]
*.

**Comment by stydxm** [comment]
> *.

👌
